name: ShellCheck Report
description: Run ShellCheck and generate a table report

author: James

inputs:
  path:
    description: Files or directories to scan
    required: false
    default: "."

  severity:
    description: Minimum ShellCheck severity
    required: false
    default: "style"

outputs:
  issues:
    description: Number of ShellCheck issues
    value: ${{ steps.shellcheck-report.outputs.issues }}

runs:
  using: composite
  steps:
    - name: Run ShellCheck Report
      id: shellcheck-report
      shell: bash
      env:
        INPUT_PATH: ${{ inputs.path }}
        INPUT_SEVERITY: ${{ inputs.severity }}
      run: python3 "${{ github.action_path }}/src/main.py"

branding:
  icon: check-circle
  color: green